# Generated by Django 5.2.12 on 2026-03-19 16:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ps_limit', models.CharField(max_length=100)),
                ('crime_number', models.CharField(max_length=100)),
                ('section_of_law', models.CharField(max_length=200)),
                ('date_of_occurrence', models.DateField()),
                ('date_of_registration', models.DateField()),
                ('complainant_name', models.CharField(max_length=200)),
                ('accused_details', models.TextField()),
                ('gist_of_case', models.TextField()),
                ('current_stage', models.CharField(choices=[('UI', 'Under Investigation'), ('PT', 'Pending Trial'), ('HC', 'Pending before High Court'), ('SC', 'Pending before Supreme Court'), ('CC', 'Case Closed')], default='UI', max_length=2)),
                ('action_to_be_taken', models.TextField()),
                ('date_of_first_updation', models.DateTimeField(auto_now_add=True)),
                ('branch', models.CharField(max_length=10)),
                ('all_officers', models.ManyToManyField(blank=True, related_name='handled_cases', to=settings.AUTH_USER_MODEL)),
                ('case_holding_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL)),
                ('current_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaseHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='cases.case')),
                ('from_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers_given', to=settings.AUTH_USER_MODEL)),
                ('to_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers_received', to=settings.AUTH_USER_MODEL)),
                ('transferred_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers_authorized', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CaseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_by', models.CharField(max_length=150)),
                ('branch', models.CharField(blank=True, max_length=50)),
                ('field_changed', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('block_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('prev_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('block_index', models.PositiveIntegerField(default=0, editable=False)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='cases.case')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
