# Generated by Django 5.2.12 on 2026-03-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_caseprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='forensic_evidences',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='case',
            name='major_improvements',
            field=models.TextField(blank=True, default=''),
        ),
    ]
