# Generated by Django 5.2.3 on 2026-03-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_case_forensic_evidences_case_major_improvements'),
    ]

    operations = [
        migrations.AddField(
            model_name='caselog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caselog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
